### ISSUE TITLE
Not working for android

### ISSUE THREAD

**Issue by rexlow** [jacklam718/react-native-action-sheet-component#1]
Integrated in my app, works for iOS 10.2 but not on android

**Comment by jacklam718** [comment]
@rexlow thanks for reporting the issue. I'll investigate it.

**Comment by rexlow** [comment]
@jacklam718 Should you need any leads, here's my repo 
https://github.com/rexlow/Castle/blob/master/src/containers/tabContainers/AddExpenses.js

**Comment by jacklam718** [comment]
@rexlow Thank you!

**Comment by jacklam718** [comment]
@rexlow sorry I still have no idea why it doesn't work on android.

**Comment by jmancherje** [comment]
Any updates? I would really like to use this but I'm trying to stick to cross platform components as long as possible.

**Comment by arstiefel** [comment]
I get the following error on Android build:

```
error: bundling: ReferenceError: Unknown plugin "flow-react-proptypes" specified in "../mobile/node_modules/react-native-action-sheet-component/.babelrc.env.development" at 0, attempted to resolve relative to "../mobile/node_modules/react-native-action-sheet-component"
```

**Comment by jacklam718** [comment]
@stief510 Are you still getting that error? Just want to clarify.

**Comment by arstiefel** [comment]
@jacklam718 I had to do `npm i babel-plugin-flow-react-proptypes` to my own package.json

**Comment by jacklam718** [comment]
@stief510 It So weird 🤔  I already declared that plugin as dev env and I already point to build version in `package.json` https://github.com/jacklam718/react-native-action-sheet-component/blob/master/package.json#L5

**Comment by jacklam718** [comment]
@rexlow I've fixed the issue please install latest version.
