### ISSUE TITLE
installed the wrong version package

### ISSUE THREAD

**Issue by alz10** [jacklam718/react-native-action-sheet-component#17]
`npm install --save react-native-action-sheet-component`

It gave the lower version package which is 0.0.36 not 0.1.48

**Comment by alz10** [comment]
![untitled](https://user-images.githubusercontent.com/38030623/52063717-fec84200-2527-11e9-8b07-7642e1f86ffe.png)

**Comment by alz10** [comment]
installing at a specific version is not working too... Seriously?

![untitled](https://user-images.githubusercontent.com/38030623/52063832-320ad100-2528-11e9-8f94-fdd1fdef8580.png)

**Comment by marla-singer** [comment]
@jacklam718 Hi! You forgot to update version in npm. Please do it
