### ISSUE TITLE
Not appearing on Android

### ISSUE THREAD

**Issue by arstiefel** [jacklam718/react-native-action-sheet-component#6]
I got the build working but the component is not showing on Android like it does for iOS

**Comment by jacklam718** [comment]
@stief510 seems duplicated wtih #1 so I'll close this

**Comment by arstiefel** [comment]
@jacklam718 #1 does not specify what the problem is. `Does not work` was not clear to me.

**Comment by jacklam718** [comment]
@stief510 OK. I'll reopen the this.

**Comment by jacklam718** [comment]
@stief510 I've fixed the issue please install the latest version.
