### ISSUE TITLE
Wrong position when using Icons

### ISSUE THREAD

**Issue by dNadiia** [jacklam718/react-native-action-sheet-component#8]
ActionSheet has 3 items, every with icon in size 42, position: doesn't matter, problem is in both.
Initial position is wrong, first (for top position is last) item is visible:
![start_position](https://user-images.githubusercontent.com/12046657/32694439-739bf138-c748-11e7-8dc2-e83aff6382ca.png)
If 'Show' appearing works correctly:
![end_position](https://user-images.githubusercontent.com/12046657/32694442-9e8e5d4a-c748-11e7-9b20-5b0ed9cc195f.png)
If 'Hide' after that position will be right. Problem only with initial position.

**Comment by dNadiia** [comment]
How to fix that?

**Comment by LucasMonteiro1** [comment]
I have the same problem, please merge PR opened

**Comment by jacklam718** [comment]
@LucasMonteiro1  @dNadiia Sorry, I forgot have pending pull requests here. I will review and test ASAP.

**Comment by jacklam718** [comment]
@dNadiia Thanks for your PR.

**Comment by jacklam718** [comment]
Fixed in version `v0.0.35` @LucasMonteiro1
